### ISSUE TITLE
Unable to install nokogumbo gem on Mac

### ISSUE THREAD

**Issue by erajanraja24** [rubys/nokogumbo#180]
I'm on MacOS Big Sur 11.4

Getting below error when I try to install nokogumbo version 2.0.5

Can someone help with this
```

em::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/rajan/.rvm/gems/ruby-2.3.7/gems/nokogumbo-2.0.5/ext/nokogumbo
/Users/rajan/.rvm/rubies/ruby-2.3.7/bin/ruby -r ./siteconf20211020-4764-1aion9c.rb extconf.rb --use-system-libraries
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/rajan/.rvm/rubies/ruby-2.3.7/bin/$(RUBY_BASE_NAME)
/Users/rajan/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- nokogiri/nokogiri
(LoadError)
        from /Users/rajan/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /Users/rajan/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /Users/rajan/.rvm/gems/ruby-2.3.7/gems/nokogiri-1.12.4-x86_64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
        from /Users/rajan/.rvm/gems/ruby-2.3.7/gems/nokogiri-1.12.4-x86_64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
        from /Users/rajan/.rvm/gems/ruby-2.3.7/gems/nokogiri-1.12.4-x86_64-darwin/lib/nokogiri.rb:11:in `require_relative'
        from /Users/rajan/.rvm/gems/ruby-2.3.7/gems/nokogiri-1.12.4-x86_64-darwin/lib/nokogiri.rb:11:in `<top (required)>'
        from /Users/rajan/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /Users/rajan/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /Users/rajan/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from extconf.rb:4:in `<main>'

extconf failed, exit code 1
```
Ruby version - 2.3.7

Tried below approaches but shouldn't help

```
gem install nokogumbo -v '2.0.5' -- --use-system-libraries

gem install nokogumbo -v '2.0.5' -- --use-system-libraries=true --with-xml2-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libxml2/
```

**Comment by flavorjones** [comment]
Hi @erajanraja24, sorry you're having problems, I'll try to help.

Can you reply with the output from `nokogiri -v` and `gem env`, please?

**Comment by flavorjones** [comment]
OK, it looks like the Nokogiri installation is in a bad state. Can you please un-install all versions of Nokogiri and then try `gem install nokogumbo` again?
