### ISSUE TITLE
gem build fails on OSX behind proxy

### ISSUE THREAD

**Issue by newton10471** [rubys/nokogumbo#26]
`$ gem install nokogumbo -v '1.4.1'` results in:

```
Fetching: nokogumbo-1.4.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing nokogumbo:
  ERROR: Failed to build gem native extension.

    /Users/newton10471/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150716-54106-14uit7d.rb extconf.rb
checking for xmlNewDoc() in -lxml2... yes
checking for nokogiri.h in /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/nokogiri-1.6.6.2/ext/nokogiri... no
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
checking for gzdopen() in -lz... yes
checking for iconv... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.2.

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
ERROR: Operation timed out - connect(2) for "ftp.xmlsoft.org" port 21
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
  --with-opt-dir
  --without-opt-dir
  --with-opt-include
  --without-opt-include=${opt-dir}/include
  --with-opt-lib
  --without-opt-lib=${opt-dir}/lib
  --with-make-prog
  --without-make-prog
  --srcdir=.
  --curdir
  --ruby=/Users/newton10471/.rvm/rubies/ruby-2.1.5/bin/ruby
  --with-xml2lib
  --without-xml2lib
  --with-libxml-2.0-config
 --without-libxml-2.0-config
  --with-pkg-config
  --without-pkg-config
  --help
  --clean
  --use-system-libraries
  --enable-static
  --disable-static
  --with-zlib-dir
  --without-zlib-dir
  --with-zlib-include
  --without-zlib-include=${zlib-dir}/include
  --with-zlib-lib
  --without-zlib-lib=${zlib-dir}/lib
  --enable-cross-build
  --disable-cross-build
/Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/mini_portile-0.6.2/lib/mini_portile.rb:319:in `rescue in download_file': Failed to complete download task (RuntimeError)
  from /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/mini_portile-0.6.2/lib/mini_portile.rb:309:in `download_file'
  from /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/mini_portile-0.6.2/lib/mini_portile.rb:28:in `block in download'
  from /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/mini_portile-0.6.2/lib/mini_portile.rb:26:in `each'
  from /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/mini_portile-0.6.2/lib/mini_portile.rb:26:in `download'
  from /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/mini_portile-0.6.2/lib/mini_portile.rb:106:in `cook'
  from /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/nokogiri-1.6.6.2/ext/nokogiri/extconf.rb:278:in `block in process_recipe'
  from /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/nokogiri-1.6.6.2/ext/nokogiri/extconf.rb:177:in `tap'
  from /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/nokogiri-1.6.6.2/ext/nokogiri/extconf.rb:177:in `process_recipe'
  from /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/nokogiri-1.6.6.2/ext/nokogiri/extconf.rb:475:in `<top (required)>'
  from /Users/newton10471/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/newton10471/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from extconf.rb:17:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/gems/nokogumbo-1.4.1 for inspection.
Results logged to /Users/newton10471/.rvm/gems/ruby-2.1.5@mygemset/extensions/x86_64-darwin-14/2.1.0-static/nokogumbo-1.4.1/gem_make.out
```

My https_proxy and http_proxy variables are set to the proper proxies, such that other gems build just fine.  'gem install nokogiri' works.  'curl ftp.xmlsoft.org' returns html as well.  It looks to me like whatever is trying to contact ftp.xmlsoft.org is doing so without the proxy settings.

**Comment by newton10471** [comment]
This appears to have been due to some conflicting Homebrew package on my Mac.  I uninstalled all unnecessary brew packages, and reinstalled the ones I needed, and the problem went away.
