### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by staugaard** [rubys/nokogumbo#39]
All versions after version 1.4.3 fail to compile on my machine OSX.

It looks like you are using an undeclared constant (GUMBO_NODE_TEMPLATE ) maybe?
Here is the output:

```
➜  ~ gem install nokogumbo -v 1.4.7
Fetching: nokogumbo-1.4.7.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing nokogumbo:
    ERROR: Failed to build gem native extension.

    /Users/staugaard/.rubies/ruby-2.2.2/bin/ruby -r ./siteconf20160104-53286-8m6nee.rb extconf.rb
checking for xmlNewDoc() in -lxml2... yes
checking for nokogiri.h in /Users/staugaard/.gem/ruby/2.2.2/gems/nokogiri-1.6.6.2.1/ext/nokogiri... yes
checking for nokogiri.h in /Users/staugaard/.gem/ruby/2.2.2/gems/nokogiri-1.6.6.2.1/ext/nokogiri... yes
checking for gumbo_parse() in -lgumbo... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling nokogumbo.c
In file included from nokogumbo.c:28:
/Users/staugaard/.gem/ruby/2.2.2/gems/nokogiri-1.6.6.2.1/ext/nokogiri/nokogiri.h:13:9: warning: '_GNU_SOURCE' macro redefined [-Wmacro-redefined]
#define _GNU_SOURCE
        ^
/Users/staugaard/.rubies/ruby-2.2.2/include/ruby-2.2.0/x86_64-darwin14/ruby/config.h:17:9: note: previous definition is here
#define _GNU_SOURCE 1
        ^
nokogumbo.c:115:12: warning: assigning to 'char *' from 'const char [7]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        ns = "xlink:";
           ^ ~~~~~~~~
nokogumbo.c:119:12: warning: assigning to 'char *' from 'const char [5]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        ns = "xml:";
           ^ ~~~~~~
nokogumbo.c:123:12: warning: assigning to 'char *' from 'const char [7]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        ns = "xmlns:";
           ^ ~~~~~~~~
nokogumbo.c:160:12: error: use of undeclared identifier 'GUMBO_NODE_TEMPLATE'; did you mean 'GUMBO_TAG_TEMPLATE'?
      case GUMBO_NODE_TEMPLATE:
           ^~~~~~~~~~~~~~~~~~~
           GUMBO_TAG_TEMPLATE
/usr/local/include/gumbo.h:172:3: note: 'GUMBO_TAG_TEMPLATE' declared here
  GUMBO_TAG_TEMPLATE,
  ^
nokogumbo.c:160:12: warning: case value not in enumerated type 'GumboNodeType' [-Wswitch]
      case GUMBO_NODE_TEMPLATE:
           ^
nokogumbo.c:110:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
  for (int i=0; i < attrs->length; i++) {
                ~ ^ ~~~~~~~~~~~~~
nokogumbo.c:132:47: warning: comparison of integers of different signs: 'unsigned long' and 'int' [-Wsign-compare]
      if (strlen(ns) + strlen(attr->name) + 1 > namelen) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~
nokogumbo.c:138:51: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
        namelen = strlen(ns) + strlen(attr->name) + 1;
                ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
nokogumbo.c:153:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
  for (int i=0; i < children->length; i++) {
                ~ ^ ~~~~~~~~~~~~~~~~
9 warnings and 1 error generated.
make: *** [nokogumbo.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/staugaard/.gem/ruby/2.2.2/gems/nokogumbo-1.4.7 for inspection.
Results logged to /Users/staugaard/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/nokogumbo-1.4.7/gem_make.out
```

**Comment by rubys** [comment]
Not a solution, just some data: `GUMBO_NODE_TEMPLATE` was introduced in https://github.com/google/gumbo-parser/releases/tag/v0.10.0 which was released on Apr 30, 2015.  So the question is: why/how are you picking up an old version of gumbo?

For reference:

```
rubys@rubyimac:~$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.2 (15C50)
      Kernel Version: Darwin 15.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Sam’s iMac
      User Name: Sam Ruby (rubys)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 11 days 54 minutes

rubys@rubyimac:~$ gem list nokogumbo

*** LOCAL GEMS ***

nokogumbo (1.4.7, 1.4.6, 1.4.1, 1.2.0)
```

**Comment by staugaard** [comment]
Ahh found the issue I had installed the gumbo-parser with homebrew and your gem was picking it up.

So I did a `brew uninstall gumbo-parser` and after that it worked.

**Comment by juggy** [comment]
I have similar compile error:

```
Building native extensions.  This could take a while...
ERROR:  Error installing nokogumbo:
	ERROR: Failed to build gem native extension.

    /Users/juggy/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20160208-71697-zffsiy.rb extconf.rb
checking for xmlNewDoc() in -lxml2... yes
checking for nokogiri.h in /Users/juggy/.rvm/gems/ruby-2.2.3@airpr-analyst/gems/nokogiri-1.6.0/ext/nokogiri... yes
checking for nokogiri.h in /Users/juggy/.rvm/gems/ruby-2.2.3@airpr-analyst/gems/nokogiri-1.6.0/ext/nokogiri... yes
checking for gumbo_parse() in -lgumbo... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling nokogumbo.c
In file included from nokogumbo.c:28:
/Users/juggy/.rvm/gems/ruby-2.2.3@airpr-analyst/gems/nokogiri-1.6.0/ext/nokogiri/nokogiri.h:13:9: warning: '_GNU_SOURCE' macro redefined [-Wmacro-redefined]
#define _GNU_SOURCE
        ^
/Users/juggy/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/x86_64-darwin15/ruby/config.h:17:9: note: previous definition is here
#define _GNU_SOURCE 1
        ^
nokogumbo.c:115:12: warning: assigning to 'char *' from 'const char [7]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        ns = "xlink:";
           ^ ~~~~~~~~
nokogumbo.c:119:12: warning: assigning to 'char *' from 'const char [5]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        ns = "xml:";
           ^ ~~~~~~
nokogumbo.c:123:12: warning: assigning to 'char *' from 'const char [7]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        ns = "xmlns:";
           ^ ~~~~~~~~
nokogumbo.c:110:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
  for (int i=0; i < attrs->length; i++) {
                ~ ^ ~~~~~~~~~~~~~
nokogumbo.c:132:47: warning: comparison of integers of different signs: 'unsigned long' and 'int' [-Wsign-compare]
      if (strlen(ns) + strlen(attr->name) + 1 > namelen) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~
nokogumbo.c:138:51: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
        namelen = strlen(ns) + strlen(attr->name) + 1;
                ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
nokogumbo.c:153:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
  for (int i=0; i < children->length; i++) {
                ~ ^ ~~~~~~~~~~~~~~~~
8 warnings generated.
linking shared-object nokogumboc.bundle
ld: warning: directory not found for option '-L/usr/local/opt/readline/lib'
ld: warning: directory not found for option '-L/usr/local/opt/readline/lib'
ld: warning: directory not found for option '-L/usr/local/opt/readline/lib'
Undefined symbols for architecture x86_64:
  "_Nokogiri_wrap_xml_document", referenced from:
      _parse in nokogumbo.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [nokogumboc.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/juggy/.rvm/gems/ruby-2.2.3@airpr-analyst/gems/nokogumbo-1.4.7 for inspection.
Results logged to /Users/juggy/.rvm/gems/ruby-2.2.3@airpr-analyst/extensions/x86_64-darwin-15/2.2.0/nokogumbo-1.4.7/gem_make.out
```

What do you make of this?

**Comment by sayyl** [comment]
I am also getting a similar compilation error:
```
ERROR:  Error installing nokogumbo:
	ERROR: Failed to build gem native extension.

    /Users/samlee/.rbenv/versions/2.1.2/bin/ruby extconf.rb
checking for xmlNewDoc() in -lxml2... yes
checking for nokogiri.h in /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1/ext/nokogiri... no
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for iconv.h... yes
checking for gzdopen() in -lz... yes
checking for iconv... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.4.

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.4.tar.gz into tmp/x86_64-apple-darwin14.5.0/ports/libxml2/2.9.4... OK
Running 'configure' for libxml2 2.9.4... OK
Running 'compile' for libxml2 2.9.4... ERROR, review '/Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogumbo-1.4.10/ext/nokogumboc/tmp/x86_64-apple-darwin14.5.0/ports/libxml2/2.9.4/compile.log' to see what happened. Last lines are:
========================================================================
    unsigned short* in = (unsigned short*) inb;
                         ^~~~~~~~~~~~~~~~~~~~~
encoding.c:815:27: warning: cast from 'unsigned char *' to 'unsigned short *' increases required alignment from 1 to 2 [-Wcast-align]
    unsigned short* out = (unsigned short*) outb;
                          ^~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.
  CC       error.lo
  CC       parserInternals.lo
  CC       parser.lo
  CC       tree.lo
  CC       hash.lo
  CC       list.lo
  CC       xmlIO.lo
xmlIO.c:1450:52: error: use of undeclared identifier 'LZMA_OK'
    ret =  (__libxml2_xzclose((xzFile) context) == LZMA_OK ) ? 0 : -1;
                                                   ^
1 error generated.
make[2]: *** [xmlIO.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/samlee/.rbenv/versions/2.1.2/bin/ruby
	--with-xml2lib
	--without-xml2lib
	--with-libxml-2.0-config
	--without-libxml-2.0-config
	--with-pkg-config
	--without-pkg-config
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build
/Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:366:in `block in execute': Failed to complete compile task (RuntimeError)
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in `chdir'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in `execute'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:111:in `compile'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:150:in `cook'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1/ext/nokogiri/extconf.rb:365:in `block (2 levels) in process_recipe'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1/ext/nokogiri/extconf.rb:258:in `block in chdir_for_build'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1/ext/nokogiri/extconf.rb:257:in `chdir'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1/ext/nokogiri/extconf.rb:257:in `chdir_for_build'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1/ext/nokogiri/extconf.rb:364:in `block in process_recipe'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1/ext/nokogiri/extconf.rb:263:in `tap'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1/ext/nokogiri/extconf.rb:263:in `process_recipe'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1/ext/nokogiri/extconf.rb:556:in `<top (required)>'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from extconf.rb:17:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogumbo-1.4.10 for inspection.
Results logged to /Users/samlee/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/nokogumbo-1.4.10/gem_make.out
```

I've tried installing with `sudo gem install nokogiri -- --use-system-libraries --with-xml2-config=/path/to/xml2-config --with-xslt-config=/path/to/xslt-config` but got the same result. Any help?

**Comment by flavorjones** [comment]
@sayyl your problem is unrelated to the original post. Please visit the Nokogiri installation tutorial for instructions to resolve your problem:

> http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x

**Comment by flavorjones** [comment]
@juggy your problem also appears to be unrelated to the original post. It looks like you may not have Nokogiri installed properly.

@rubys I think this ticket can be closed. The OP's issue was resolved.
